server:
  port: 8090

  tomcat:
    max-http-form-post-size: 20MB

spring:
  servlet:
    multipart:
      max-file-size: 30MB  # Tama침o m치ximo por archivo
      max-request-size: 30MB  # Tama침o m치ximo de la solicitud
